export enum LocalizationDataKey {
  APP_TITLE_TEXT = 'APP_TITLE_TEXT',
  TASK_LIST_ADD_TASK_BUTTON_TEXT = 'TASK_LIST_ADD_TASK_BUTTON_TEXT',
  TASK_LIST_ADD_TASK_BUTTON_TITLE = 'TASK_LIST_ADD_TASK_BUTTON_TITLE',
  TASK_LIST_EDIT_TASK_BUTTON_TITLE = 'TASK_LIST_EDIT_TASK_BUTTON_TITLE',
  TASK_LIST_REMOVE_TASK_BUTTON_TITLE = 'TASK_LIST_REMOVE_TASK_BUTTON_TITLE',
  TASK_LIST_NO_TASKS_MESSAGE = 'TASK_LIST_NO_TASKS_MESSAGE'
}
