export enum TaskActionType {
  ADD_TASK = 'ADD_TASK',
  EDIT_TASK = 'EDIT_TASK',
  SET_TASK_COMPLETION = 'SET_TASK_COMPLETION',
  REMOVE_TASK = 'REMOVE_TASK',
  REMOVE_ALL_TASKS = 'REMOVE_ALL_TASKS',
  REMOVE_ALL_COMPLETED_TASKS = 'REMOVE_ALL_COMPLETED_TASKS',
  SET_TASKS_FILTER = 'SET_TASKS_FILTER'
}
